### ISSUE TITLE
Opt out of Google's Tracking APIs in Chrome-based browsers

### ISSUE THREAD

**Issue by naiyerasif** [Microflash/site-next#2]
Disable the following tech for Chrome-based browsers:
- FLoC (through `interest-cohort=()`)
- Topic API (through `browsing-topics=()`)
- FLEDGE API (through ` join-ad-interest-group=()` and `run-ad-auction=()`)

To do this, I need to send the following Permissions Policy HTTP response header.

```
Permissions-Policy: browsing-topics=(), interest-cohort=(), join-ad-interest-group=(), run-ad-auction=()
```

Since this site is hosted on Netlify, create a `netlify.toml` with the following setting.

```toml
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "browsing-topics=(), interest-cohort=(), join-ad-interest-group=(), run-ad-auction=()"
```

Alternatively, create a `_headers` file in the public directory.

```
/*
  Permissions-Policy: browsing-topics=(), interest-cohort=(), join-ad-interest-group=(), run-ad-auction=()
```
