### ISSUE TITLE
Opt out of Google's Topic API

### ISSUE THREAD

**Issue by naiyerasif** [Microflash/site-next#3]
To opt out of Google’s Topic API, I need to send the following Permissions Policy HTTP response header.

```
Permissions-Policy: browsing-topics=()
```

Since this site is hosted on Netlify, create a `netlify.toml` with the following setting.

```toml
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "browsing-topics=()"
```

Alternatively, create a `_headers` file in the public directory.

```
/*
  Permissions-Policy: browsing-topics=()
```
